/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 51a55e9b2408142060849839f2cee4ec)
// Runtime types generated with workerd@1.20251011.0 2025-10-08 nodejs_compat
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env {
		N8N_WEBHOOK_URL?: string;
	}
}
interface Env extends Cloudflare.Env {}

