name: Build Server on Push

on:
  push:
    branches:
      - main
    paths:
      - fax-me-maybe-server/**
  workflow_dispatch:


jobs:
    build-server:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Change to server directory
          run: cd fax-me-maybe-server

        - name: Install NodeJS
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: 'npm'

        - name: Run Vite Bundler
          run: npm run build

        - name: Build & Deploy Worker
          uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
