name: Build Client on Push

on:
  push:
    branches:
      - main
    paths:
      - fax-me-maybe-client/**

jobs:
  build-client:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]
          arch: [amd64, arm64]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Github Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: deadpackets
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            platforms: linux/${{ matrix.arch }}
            push: true
            tags: ghcr.io/deadpackets/fax-me-maybe-client:latest
